name: CI/CD Auto Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 157.15.124.192
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            /usr/bin/bash /opt/deploy.sh
